### ISSUE TITLE
Enable setting allowed IPs in command line

### ISSUE THREAD

**Issue by trojal** [herenow/wsProxy#2]
When using npm install wsproxy, we are not compiling from source. It's unclear how to edit allowed.js to specify the destination IPs with this method.

It would be nice to be able to set the allowed IP list via command line when starting wsproxy.

**Comment by herenow** [comment]
I'll get on this asap :)

**Comment by herenow** [comment]
I've added an adhoc solution for now, it's it no way ideal, but it seems to work :)

As soon as I have more time I plan on refactoring this code, actually I would like to refactor the entire wsProxy code, if roBrowser lives on.
