### ISSUE TITLE
 Wsproxy gets only with the following message [Status]: Starting wsProxy on port 5999 

### ISSUE THREAD

**Issue by marcosdavids** [herenow/wsProxy#3]
![wsproxy](https://cloud.githubusercontent.com/assets/23299427/26032428/064ad864-386a-11e7-8a4f-e97861ac131a.png)

Wsproxy gets only with the following message [Status]: Starting wsProxy on port 5999 ... what's wrong? thank you

**Comment by herenow** [comment]
Everything seems fine, is roBrowser not connecting to it? How is your roBrowser configured? Please paste your roBrowser config.

**Comment by marcosdavids** [comment]
I can log in but create the character I get error disconnected from the server
`[Status]: Connection accepted from '149.56.147.107:6121'.
[Info]: solicitacao de conexao - conta_id:2000000/login_id1:1959735862/login_id2:1403307126
[Info]: Carregando Personagem (2000000)
[Info]: Connection closed from '149.56.147.107:6900'.
[Info]: Connection closed from '::ffff:179.176.101.153'.
[Info]: Conexao fechada para '149.56.147.107'.
[Info]: Connection closed from '149.56.147.107:6900'.
[Info]: Connection closed from '::ffff:179.176.101.153'.
[Erro]: chr->parse_char: Recebido pacote desconhecido 0x970 ip '149.56.147.107'! Desconectando...
[Info]: Connection closed from '149.56.147.107:6121'.
[Info]: Connection closed from '::ffff:179.176.101.153'.
[Info]: Connection closed from '149.56.147.107:6121'.
[Info]: Connection closed from '::ffff:179.176.101.153'.

`

**Comment by herenow** [comment]
Post the config `ROConfig`, you probably have it set in your index.html.

**Comment by herenow** [comment]
By the way, this is probably not a wsProxy problem.

```
chr->parse_char: Recebido pacote desconhecido 0x970 ip '149.56.147.107'
```

This looks like a communication problem between roBrowser (client), and the emulator (server).
